//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReport2.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckedInOut
    {
        public int CheckedInId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> CheckedInDate { get; set; }
        public Nullable<int> Staying { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> RoomTypeId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Remain { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
